name: core
version: 0.0.1
publish_to: none
description: Project core module

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.6.7
  dio: ^5.4.0
  logger: ^2.0.2
  http: ^1.2.1
  easy_localization: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - resources/lang/