name: domain
version: 0.0.1
publish_to: none
description: Project domain module

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  core:
    path: ../core
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.11
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
